steps:
  # Step 1: Definir nombre del servicio según la rama
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'set-service-name'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" ]]; then
          echo "laravel-prod" > /workspace/service_name.txt
        else
          echo "laravel-staging" > /workspace/service_name.txt
        fi

  # Step 2: Build de la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/laravel_app:$BRANCH_NAME-$SHORT_SHA'
      - '.'

  # Step 3: Push de la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/laravel_app:$BRANCH_NAME-$SHORT_SHA'

  # Step 4: Despliegue en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_NAME=$(cat /workspace/service_name.txt)
        gcloud run deploy $SERVICE_NAME \
          --image ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/laravel_app:$BRANCH_NAME-$SHORT_SHA \
          --region ${_DEPLOY_REGION} \
          --platform ${_PLATFORM} \
          --allow-unauthenticated

images:
  - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/laravel_app:$BRANCH_NAME-$SHORT_SHA'
