steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/devcode-457115/laravel_app:staging-$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/devcode-457115/laravel_app:staging-$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'laravel-service',
      '--image', 'gcr.io/devcode-457115/laravel_app:staging-$SHORT_SHA',
      '--region', 'us-east4',
      '--platform', 'managed',
      '--allow-unauthenticated',

      # Este formato monta el secreto como archivo en /secrets/laravel_env
      '--set-secrets=laravel_env=laravel-env:latest:file',

      # Ruta donde se montará el archivo secreto (dentro del contenedor)
      '--execution-environment=gen2'  # necesario para usar secretos
    ]

images:
  - gcr.io/devcode-457115/laravel_app:staging-$SHORT_SHA
